version: '3.8'

services:
  frontend:
    container_name: calculator-frontend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production